// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1FevAEUfg7u_tmhjPKGLJfVFBiQaghCY',
    appId: '1:218937674834:web:2961695e7663494adb638b',
    messagingSenderId: '218937674834',
    projectId: 'petmonitoringsystem-729da',
    authDomain: 'petmonitoringsystem-729da.firebaseapp.com',
    storageBucket: 'petmonitoringsystem-729da.appspot.com',
    measurementId: 'G-D4TRM99C0G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-IrhHSqB0m6wiGAENuZkQgI08Zr54m0I',
    appId: '1:218937674834:android:bc76855286272274db638b',
    messagingSenderId: '218937674834',
    projectId: 'petmonitoringsystem-729da',
    storageBucket: 'petmonitoringsystem-729da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCyVMmO71eLd8Rl_C9zVwRL-nk4L4AvJo',
    appId: '1:218937674834:ios:4c4a7b2b05a386ebdb638b',
    messagingSenderId: '218937674834',
    projectId: 'petmonitoringsystem-729da',
    storageBucket: 'petmonitoringsystem-729da.appspot.com',
    androidClientId: '218937674834-4ehm7bgousop6d77ukk4levcscqe8lsm.apps.googleusercontent.com',
    iosClientId: '218937674834-r7vgtuv23i47j245a8vc85ig95mqve3m.apps.googleusercontent.com',
    iosBundleId: 'com.example.petapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCyVMmO71eLd8Rl_C9zVwRL-nk4L4AvJo',
    appId: '1:218937674834:ios:4c4a7b2b05a386ebdb638b',
    messagingSenderId: '218937674834',
    projectId: 'petmonitoringsystem-729da',
    storageBucket: 'petmonitoringsystem-729da.appspot.com',
    androidClientId: '218937674834-4ehm7bgousop6d77ukk4levcscqe8lsm.apps.googleusercontent.com',
    iosClientId: '218937674834-r7vgtuv23i47j245a8vc85ig95mqve3m.apps.googleusercontent.com',
    iosBundleId: 'com.example.petapp',
  );
}
